scrape_configs:
  - job_name: 'demo'
    scrape_interval: 3s
    static_configs:
      - targets: ['otelcollector:7777']
  - job_name: 'collector'
    scrape_interval: 1000s
    static_configs:
      - targets: ['otelcollector:8888']     
  - job_name: 'self'
    scrape_interval: 1000s
    static_configs:
      - targets: ['localhost:9090']